language: node_js
node_js:
  - "lts/*"

matrix:
  fast_finish: true

cache:
  directories:
    - node_modules

before_install:
  - npm prune

script:
  - npm run test-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 16889061-c2f4-4aba-8838-38d64b7c967d